### PR TITLE
Lang file handler

### PR DESCRIPTION
**Pull request by Lennart99**

### CODE REVIEW

**Review by KevinDaGame — APPROVED** [review]
Looks good, though I have a question. Where are colours parsed?

**Comment by Lennart99** [comment]
Shade failed, will be fixed by #28

**Comment by Lennart99** [comment]
Doesn't work for paper 1.16 right now, because of sync issues between the adventure dependency in plugin and paper, will need to fix that

**Comment by Lennart99** [comment]
Now works again on both paper and spigot builds, all the way back to 1.16.5

**Review by KevinDaGame — APPROVED** [review]

**Pull request merged**
